// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0cyo0i8oTpQ0tJfOVCHfxMOKXbsuWrw',
    appId: '1:432946371252:web:fdbc418636830a099755e1',
    messagingSenderId: '432946371252',
    projectId: 'mentimeter-6c64b',
    authDomain: 'mentimeter-6c64b.firebaseapp.com',
    storageBucket: 'mentimeter-6c64b.firebasestorage.app',
    measurementId: 'G-24718L8RXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvNGMiaNPDThoArmLPMp-AgYyOIKwK70c',
    appId: '1:432946371252:android:de866d840c41bac49755e1',
    messagingSenderId: '432946371252',
    projectId: 'mentimeter-6c64b',
    storageBucket: 'mentimeter-6c64b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONbOIe28pUBAWzTfyQQyOT_Or8hlhUGI',
    appId: '1:432946371252:ios:6d3b92e79860007b9755e1',
    messagingSenderId: '432946371252',
    projectId: 'mentimeter-6c64b',
    storageBucket: 'mentimeter-6c64b.firebasestorage.app',
    iosBundleId: 'com.example.participantapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONbOIe28pUBAWzTfyQQyOT_Or8hlhUGI',
    appId: '1:432946371252:ios:6d3b92e79860007b9755e1',
    messagingSenderId: '432946371252',
    projectId: 'mentimeter-6c64b',
    storageBucket: 'mentimeter-6c64b.firebasestorage.app',
    iosBundleId: 'com.example.participantapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX0cyo0i8oTpQ0tJfOVCHfxMOKXbsuWrw',
    appId: '1:432946371252:web:451831bdc28e18019755e1',
    messagingSenderId: '432946371252',
    projectId: 'mentimeter-6c64b',
    authDomain: 'mentimeter-6c64b.firebaseapp.com',
    storageBucket: 'mentimeter-6c64b.firebasestorage.app',
    measurementId: 'G-DZM6PMDG1Y',
  );
}
